### ISSUE TITLE
Error at runtime

### ISSUE THREAD

**Issue by Wildhoney** [theopak/react-parallax-card#1]
[Error in example](https://esnextb.in/?gist=86887f92782b7df4698147f305860a1d) :bug::

> Uncaught TypeError: Cannot read property 'style' of undefined

**Comment by theopak** [comment]
Hi @Wildhoney, thanks for pointing this out and for the quick reproduction case. I see that the error is caused by a bug in this package which makes it unable to render a single child node. I'll fix this soon!

Meanwhile, you can use the current version by adding at least one other node as a direct child:

```js
  <ParallaxCard
    label='Label (optional)'
    enableRotate
    style={{ margin: '0 auto', width: 240, height: 240 }}>
    <img src='https://s3-us-west-1.amazonaws.com/tachyonsio/img/Blonde-Frank_Ocean.jpeg' width='240' role='presentation' />
    <div />
  </ParallaxCard>
```

**Comment by Wildhoney** [comment]
Thanks for the temporary fix @theopak 👍

**Comment by 3DJakob** [comment]
@theopak  This issue still persists, please fix it and publish a new version!
